GET http://localhost:4000/notes/675f3b061792815cfc8fb6d8/overdue

###

POST  http://localhost:4000/notes/675f3b061792815cfc8fb6d8
Content-Type: application/json

{
    "title": "Meeting with Team",
    "description": "Discuss project milestones and deadlines.",
    "day": "2024-12-20",
    "hour": 15,
    "min": 30,
    "status": "overdue"
}

###

DELETE http://localhost:4000/users