GET http://localhost:4000/notes/676e9153a4fed6e39659aadf

###

POST  http://localhost:4000/notes/676e9153a4fed6e39659aadf
Content-Type: application/json

{
    "title": "zhfozeh",
    "description": "Description test z",
    "day": "2023-12-30",
    "hour": 15,
    "min": 30,
    "status": "incomplete",
    "userId": "676e9153a4fed6e39659aadf"
}

###

DELETE http://localhost:4000/users/676ad46e76662aaffd1cf439