GET http://localhost:4000/users

###

PATCH http://localhost:4000/users/password/676e9153a4fed6e39659aadf
Content-Type: application/json

{
    "password": "hhhhhhhh",
    "newPassword": "12345678"
}

###

DELETE http://localhost:4000/users/676ad46e76662aaffd1cf439